// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class LoginTesztekTest
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp] // A Browser driver-t elõkészítem használatra
    public void SetUp()
    {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown] // A TearDown-al automatikusan bezárhatjuk a böngészõt
    protected void TearDown()
    {
        driver.Quit();
    }
    [Test]
    public void loginEmailRossz()
    {
        driver.Navigate().GoToUrl("https://localhost:44354/"); // Elnavigálunk a cél oldalra
        driver.Manage().Window.Size = new System.Drawing.Size(1050, 964); // Megadott nagyságú ablakban nyitjuk meg
        driver.FindElement(By.Id("but")).Click(); // Megkeressük Id alapján a Belépés gombot, és rákattintunk
        driver.FindElement(By.Name("email")).Click(); // Megkeressük az email mezõt, majd belekattintunk.
        driver.FindElement(By.Name("email")).SendKeys("rosszemail.hu"); // A mezõbe beleírunk egy rossz-email formátumot.
        driver.FindElement(By.Name("password")).Click(); // Majd a jelszó mezõre kattintunk
        driver.FindElement(By.Name("password")).SendKeys("asd"); // Beírunk egy jelszavat a mezõbe
        driver.FindElement(By.Id("login-submit")).Click(); // Megkeressük a Belépés gombot, és rákattintunk
    }
    [Test]
    public void loginEmailUres()
    {
        driver.Navigate().GoToUrl("https://localhost:44354/"); // Elnavigálunk a cél oldalra
        driver.Manage().Window.Size = new System.Drawing.Size(1050, 964); // Megadott nagyságú ablakban nyitjuk meg
        driver.FindElement(By.Id("but")).Click(); // Megkeressük Id alapján a Belépés gombot, és rákattintunk
        driver.FindElement(By.Name("email")).Click();// Az email mezõbe kattintunk de üresen hagyjuk. 
        driver.FindElement(By.Name("password")).Click();// Az jelszó mezõbe kattintunk.
        driver.FindElement(By.Name("password")).SendKeys("asd");// Beírunk egy jelszavat a mezõbe
        driver.FindElement(By.Id("login-submit")).Click();// Megkeressük a Belépés gombot, és rákattintunk
        driver.FindElement(By.Id("thebutton")).Click();// A megjelenõ gombra kattintunk
    }
    [Test]
    public void loginJelszoElfelejtve()
    {
        driver.Navigate().GoToUrl("https://localhost:44354/"); // Elnavigálunk a cél oldalra
        driver.Manage().Window.Size = new System.Drawing.Size(1050, 964); // Megadott nagyságú ablakban nyitjuk meg
        driver.FindElement(By.Id("but")).Click(); // Megkeressük Id alapján a Belépés gombot, és rákattintunk
        driver.FindElement(By.Name("email")).Click();// Az email mezõbe kattintunk.
        driver.FindElement(By.Name("email")).SendKeys("asd@asd.hu");// Kitöltjük az email mezõt egy létezõvel.
        driver.FindElement(By.Name("password")).Click();// Az jelszó mezõbe kattintunk de üresen hagyjuk.
        driver.FindElement(By.Id("forgottenpassword")).Click(); // Az elfelejtett jelszó funkció gombra kattintunk
        driver.FindElement(By.Id("thebutton")).Click();// A megjelenõ gombra kattintunk hogy visszatérjen az Indexre
    }
    [Test]
    public void loginJelszoRossz()
    {
        driver.Navigate().GoToUrl("https://localhost:44354/"); // Elnavigálunk a cél oldalra
        driver.Manage().Window.Size = new System.Drawing.Size(1050, 964); // Megadott nagyságú ablakban nyitjuk meg
        driver.FindElement(By.Id("but")).Click(); // Megkeressük Id alapján a Belépés gombot, és rákattintunk
        driver.FindElement(By.Name("email")).Click();// Az email mezõbe kattintunk.
        driver.FindElement(By.Name("email")).SendKeys("asd@asd.hu");// Kitöltjük az email mezõt.
        driver.FindElement(By.Name("password")).Click();// Az jelszó mezõbe kattintunk.
        driver.FindElement(By.Name("password")).SendKeys("rosszjelszo");// Az jelszó mezõbe rossz jelszót adunk meg
        driver.FindElement(By.Id("login-submit")).Click(); // A Belépés gombra nyomunk
        driver.FindElement(By.Id("thebutton")).Click();// A megjelenõ gombra kattintunk
    }
    [Test]
    public void loginJelszoUres()
    {
        driver.Navigate().GoToUrl("https://localhost:44354/"); // Elnavigálunk a cél oldalra
        driver.Manage().Window.Size = new System.Drawing.Size(1050, 964); // Megadott nagyságú ablakban nyitjuk meg
        driver.FindElement(By.Id("but")).Click(); // Megkeressük Id alapján a Belépés gombot, és rákattintunk
        driver.FindElement(By.Name("email")).Click();// Az email mezõbe kattintunk.
        driver.FindElement(By.Name("email")).SendKeys("asd@asd.hu"); // Kitöltjük az email mezõt.
        driver.FindElement(By.Name("password")).Click(); // Az jelszó mezõbe kattintunk de öresen hagyjuk.
        driver.FindElement(By.Id("login-submit")).Click(); // A Belépés gombra nyomunk
        driver.FindElement(By.Id("thebutton")).Click();// A megjelenõ gombra kattintunk
    }
    [Test]
    public void loginPrivacyPolicy()
    {
        driver.Navigate().GoToUrl("https://localhost:44354/"); // Elnavigálunk a cél oldalra
        driver.Manage().Window.Size = new System.Drawing.Size(1050, 964); // Megadott nagyságú ablakban nyitjuk meg
        driver.FindElement(By.Id("but")).Click(); // Megkeressük Id alapján a Belépés gombot, és rákattintunk
        driver.FindElement(By.Id("privacy")).Click(); // Megkeressük Id alapján a Privacy-t, amire rákattintunk
        driver.FindElement(By.LinkText("Back to shop")).Click(); //Szöveges link alapján keresi a gombot és kattint.
    }
}
